name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.8
# author: Aleksander Wo≈∫niak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
